In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)
arr


[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [5]:
print("Array: ", arr)

max = np.max(arr)
print("Max of Array: ", max)

min = np.min(arr)
print("Min of Array: ", min)

idx = np.argmax(arr)
print("Index of Maz Array Element: ", idx)


Array:  [1 2 3 4 5]
Max of Array:  5
Min of Array:  1
Index of Maz Array Element:  4


In [6]:
print(arr[1:2])


[2]


In [7]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print("2D Array : \n",arr2d)

# Slicing in 2D Array, (min_row : max_row+1, min_col : max_col+1)
# In this, in the first parameter, we have slice out the 2D or 1D array according to our need.

# In below, example, If we want to slice out first 2 row elements and first 2 column elements then below slicing code will 
# be written as follows:
print("\nSliced Array:(from 0,0 to 2,2)\n ",arr2d[0:2,0:2])

2D Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced Array:(from 0,0 to 2,2)
  [[1 2]
 [4 5]]


In [9]:
# To slice from 1,1 to 2,2
# print(arr2d[1:3, 1:3])

# Extract all odd numbers from an array 1...10
# Replace all odd numbers in an array with -1
# Replace all odd numbers in an array with -1 without changing original array
# Consider a 1D Array, convert that to the 2D array of 2 rows.
# Stack the array a and b vertically (reshape function)
# Stack the array a and b horizontally (reshape function)

# Print the patter for ex, a = [1,2,3]
# op: a = [1,1,1, 2,2,2, 3,3,3,
#            1,2,3, 1,2,3, 1,2,3]
# (repeat function)

# (where function) -> for replacing 

In [10]:
# Extract all odd numbers from an array 1...10

arr = np.array([1,2,3,4,5,6,7,8,9,10])

# for i in arr:
#     if(i%2 == 0):
#         print(arr[i])

# Instead of using for loop for taking out the odd numbers, we can directly check odd numbers
# with condition and it will give the index that are true
print(arr[arr%2 != 0])

[1 3 5 7 9]


In [11]:
# Replace all odd numbers in an array with -1
arr[arr%2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [12]:
# Replace all odd numbers in an array with -1 without changing original array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array(arr[arr%2 != 0])
print(arr2)

[1 3 5 7 9]


In [13]:
# Consider a 1D Array, convert that to the 2D array of 2 rows.
a = np.arange(10);
print("Array before reshaping : ",a)
a = a.reshape(2,5)
print("Array after reshaping : \n", a)


Array before reshaping :  [0 1 2 3 4 5 6 7 8 9]
Array after reshaping : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
# Stack the array a and b vertically (reshape function)

In [15]:
# Stack the array a and b horizontally (reshape function)

In [16]:
# Print the patter for ex, a = [1,2,3]
# op: a = [1,1,1, 2,2,2, 3,3,3,
#            1,2,3, 1,2,3, 1,2,3]
# (repeat function)

ML Lab 3

In [17]:
import pandas as pd
import numpy as np

series = pd.Series()

print(series)

data = np.array(['r','a','j'])

series = pd.Series(data)

print(series)

Series([], dtype: float64)
0    r
1    a
2    j
dtype: object


/home/mllab07/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  after removing the cwd from sys.path.


In [18]:
df = pd.DataFrame()
print(df)

lst = ['Hello', 'my', 'name', 'is', 'Raj']

df = pd.DataFrame(lst)
print(df)

Empty DataFrame
Columns: []
Index: []
       0
0  Hello
1     my
2   name
3     is
4    Raj


In [19]:
arr = [[1,2,3], [4,5,6], [7,8,9]]

myVal = pd.Series(arr)

print(myVal)

myVal = pd.Series(arr, index = [["a","b","c"], ["d","e","f"], ["g","h","i"]])

print(myVal)

0    [1, 2, 3]
1    [4, 5, 6]
2    [7, 8, 9]
dtype: object
a  d  g    [1, 2, 3]
b  e  h    [4, 5, 6]
c  f  i    [7, 8, 9]
dtype: object


In [44]:
# // Confusion Matrix

actual = pd.Series([1 for _ in range(50)] + [0 for _ in range(50)], name = "Actual")
predicted = pd.Series([1 for _ in range(45)] + [0 for _ in range(55)], name = "Predicted")

In [45]:
graph = pd.crosstab(actual, predicted)
graph

Predicted   0   1
Actual           
0          50   0
1           5  45

In [48]:
# Manual Calculations:

TP = 45
FN = 5
FP = 0
TN = 50

# Precision: TP / (TP + FP)
precision = TP / (TP + FP) 
# Recall: TP / (TP + FN)
recall = TP / (TP + FN)
# Accuracy: (TP + TN) / (TP + TN + FP + FN)
accuracy= (TP + TN) / (TP + TN + FP + FN)
# F1 - Score: 2 * TP / (2 * TP + FP + FN)
f1_score = 2 * TP / (2 * TP + FP + FN)

print("Precision : ", precision)
print("Recall : ", recall)
print("Accuracy : ", accuracy)
print("F1_Score : ", f1_score)


Precision :  1.0
Recall :  0.9
Accuracy :  0.95
F1_Score :  0.9473684210526315


In [52]:
from sklearn.metrics import classification_report


cr = classification_report(actual, predicted)
print(cr)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        50
           1       1.00      0.90      0.95        50

    accuracy                           0.95       100
   macro avg       0.95      0.95      0.95       100
weighted avg       0.95      0.95      0.95       100

